/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.awt.Color;
import javax.swing.JFrame;
import biblioteca.Libros;


/**
 *
 * @author Ernesto
 */
public class MenuP extends javax.swing.JFrame {

    /**
     * Creates new form MenuP
     */
    public MenuP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSalida = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        boton_ingreso1 = new javax.swing.JLabel();
        boton_ingreso2 = new javax.swing.JLabel();
        boton_ingreso3 = new javax.swing.JLabel();
        Lbfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(370, 380));
        setName("MenuPrin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(370, 410));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalida.setBackground(new java.awt.Color(100, 180, 100));
        BotonSalida.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalida.setText("SALIR");
        BotonSalida.setFocusable(false);
        BotonSalida.setOpaque(true);
        BotonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalidaMousePressed(evt);
            }
        });
        BotonSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseMoved(evt);
            }
        });
        getContentPane().add(BotonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 40));

        Titulo.setBackground(new java.awt.Color(100, 180, 100));
        Titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("BIBLIO-TURING");
        Titulo.setToolTipText("");
        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Titulo.setOpaque(true);
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        boton_ingreso1.setBackground(new java.awt.Color(55, 55, 55));
        boton_ingreso1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        boton_ingreso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_ingreso1.setText("LIBROS");
        boton_ingreso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_ingreso1.setOpaque(true);
        boton_ingreso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ingreso1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ingreso1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ingreso1MouseExited(evt);
            }
        });
        getContentPane().add(boton_ingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, 40));

        boton_ingreso2.setBackground(new java.awt.Color(55, 55, 55));
        boton_ingreso2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_ingreso2.setForeground(new java.awt.Color(255, 255, 255));
        boton_ingreso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_ingreso2.setText("USUARIOS");
        boton_ingreso2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_ingreso2.setOpaque(true);
        boton_ingreso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ingreso2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ingreso2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ingreso2MouseExited(evt);
            }
        });
        getContentPane().add(boton_ingreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 40));

        boton_ingreso3.setBackground(new java.awt.Color(55, 55, 55));
        boton_ingreso3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_ingreso3.setForeground(new java.awt.Color(255, 255, 255));
        boton_ingreso3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_ingreso3.setText("PRESTAMOS");
        boton_ingreso3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_ingreso3.setOpaque(true);
        boton_ingreso3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ingreso3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ingreso3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ingreso3MouseExited(evt);
            }
        });
        getContentPane().add(boton_ingreso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 40));

        Lbfondo.setBackground(new java.awt.Color(55, 55, 55));
        Lbfondo.setOpaque(true);
        getContentPane().add(Lbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseEntered
     Color bColor1=new Color(151,195,151);
        BotonSalida.setBackground(bColor1);
    }//GEN-LAST:event_BotonSalidaMouseEntered

    private void BotonSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseExited
       Color bColor2=new Color(100,180,100);
        BotonSalida.setBackground(bColor2);
    }//GEN-LAST:event_BotonSalidaMouseExited

    private void BotonSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseClicked

        System.exit(0);
    }//GEN-LAST:event_BotonSalidaMouseClicked

    private void BotonSalidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseMoved
         Color bColor3=new Color(151,195,151);
        BotonSalida.setBackground(bColor3);
    }//GEN-LAST:event_BotonSalidaMouseMoved

    private void BotonSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMousePressed
     Color bColor3=new Color(171,225,171);
        BotonSalida.setBackground(bColor3);
    }//GEN-LAST:event_BotonSalidaMousePressed

    private void boton_ingreso1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso1MouseEntered

        Color bColor=new Color(100,100,100);
           boton_ingreso1.setBackground(bColor);
       
    }//GEN-LAST:event_boton_ingreso1MouseEntered

    private void boton_ingreso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso1MouseExited
       
      Color bColor=new Color(55,55,55);
            boton_ingreso1.setBackground(bColor);
    }//GEN-LAST:event_boton_ingreso1MouseExited

    private void boton_ingreso2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso2MouseEntered
       
         Color bColor=new Color(100,100,100);
           boton_ingreso2.setBackground(bColor);
    }//GEN-LAST:event_boton_ingreso2MouseEntered

    private void boton_ingreso2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso2MouseExited
     
        Color bColor=new Color(55,55,55);
            boton_ingreso2.setBackground(bColor);
    }//GEN-LAST:event_boton_ingreso2MouseExited

    private void boton_ingreso3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso3MouseEntered
        
        Color bColor=new Color(100,100,100);
           boton_ingreso3.setBackground(bColor);
    }//GEN-LAST:event_boton_ingreso3MouseEntered

    private void boton_ingreso3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso3MouseExited
        
         Color bColor=new Color(55,55,55);
            boton_ingreso3.setBackground(bColor);
    }//GEN-LAST:event_boton_ingreso3MouseExited

    private void boton_ingreso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso1MouseClicked
rootPane.setVisible(false);
       dispose();
        Libros l = new Libros();
        l.setVisible(true); 
          
              
    }//GEN-LAST:event_boton_ingreso1MouseClicked

    private void boton_ingreso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso2MouseClicked

        rootPane.setVisible(false);
       dispose();
        Usuarios u = new Usuarios();
        u.setVisible(true); 
    }//GEN-LAST:event_boton_ingreso2MouseClicked

    private void boton_ingreso3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ingreso3MouseClicked
    
         rootPane.setVisible(false);
       dispose();
        Prestamos u = new Prestamos();
        u.setVisible(true); 
    }//GEN-LAST:event_boton_ingreso3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonSalida;
    private javax.swing.JLabel Lbfondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel boton_ingreso1;
    private javax.swing.JLabel boton_ingreso2;
    private javax.swing.JLabel boton_ingreso3;
    // End of variables declaration//GEN-END:variables
}