/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaE;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Prestamos extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        Titulo = new javax.swing.JLabel();
        boton_nuevo = new javax.swing.JLabel();
        boton_editar = new javax.swing.JLabel();
        boton_borrar = new javax.swing.JLabel();
        in_codigo = new javax.swing.JTextField();
        in_fec_Prestamo = new javax.swing.JTextField();
        in_fec_Devolucion = new javax.swing.JTextField();
        in_usuario_codigo = new javax.swing.JTextField();
        in_usuario_nombre = new javax.swing.JTextField();
        in_libro_titulo = new javax.swing.JTextField();
        in_libro_codigo = new javax.swing.JTextField();
        BotonGuardado = new javax.swing.JLabel();
        BotonSalida = new javax.swing.JLabel();
        lb_aviso = new javax.swing.JLabel();
        Lbfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idprestamos", "Fec_prest", "Fec_devol", "usuarios_idusuarios", "libro_idlibro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 560, 290));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 370));

        Titulo.setBackground(new java.awt.Color(100, 180, 100));
        Titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("PRESTAMOS");
        Titulo.setToolTipText("");
        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Titulo.setOpaque(true);
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 40));

        boton_nuevo.setBackground(new java.awt.Color(55, 55, 55));
        boton_nuevo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        boton_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_nuevo.setText("NUEVO");
        boton_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_nuevo.setOpaque(true);
        boton_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseExited(evt);
            }
        });
        getContentPane().add(boton_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        boton_editar.setBackground(new java.awt.Color(55, 55, 55));
        boton_editar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_editar.setForeground(new java.awt.Color(255, 255, 255));
        boton_editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_editar.setText("EDITAR");
        boton_editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_editar.setOpaque(true);
        boton_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_editarMouseExited(evt);
            }
        });
        getContentPane().add(boton_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, 30));

        boton_borrar.setBackground(new java.awt.Color(55, 55, 55));
        boton_borrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_borrar.setForeground(new java.awt.Color(255, 255, 255));
        boton_borrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_borrar.setText("BORRAR");
        boton_borrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_borrar.setOpaque(true);
        boton_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_borrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_borrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_borrarMouseExited(evt);
            }
        });
        getContentPane().add(boton_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 80, 30));

        in_codigo.setEditable(false);
        in_codigo.setBackground(new java.awt.Color(200, 200, 200));
        in_codigo.setText("CODIGO PREST");
        in_codigo.setFocusable(false);
        in_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(in_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 90, 30));

        in_fec_Prestamo.setEditable(false);
        in_fec_Prestamo.setBackground(new java.awt.Color(200, 200, 200));
        in_fec_Prestamo.setText("FECHA DE PRESTAMO");
        in_fec_Prestamo.setFocusable(false);
        in_fec_Prestamo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                in_fec_PrestamoFocusGained(evt);
            }
        });
        getContentPane().add(in_fec_Prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 30));

        in_fec_Devolucion.setEditable(false);
        in_fec_Devolucion.setBackground(new java.awt.Color(200, 200, 200));
        in_fec_Devolucion.setText("FECHA DE DEVOLUCION");
        in_fec_Devolucion.setFocusable(false);
        in_fec_Devolucion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                in_fec_DevolucionFocusGained(evt);
            }
        });
        in_fec_Devolucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_fec_DevolucionKeyTyped(evt);
            }
        });
        getContentPane().add(in_fec_Devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 30));

        in_usuario_codigo.setEditable(false);
        in_usuario_codigo.setBackground(new java.awt.Color(200, 200, 200));
        in_usuario_codigo.setText("COD USUARIO");
        in_usuario_codigo.setFocusable(false);
        in_usuario_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_usuario_codigoActionPerformed(evt);
            }
        });
        in_usuario_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                in_usuario_codigoFocusGained(evt);
            }
        });
        in_usuario_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_usuario_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(in_usuario_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 90, 30));

        in_usuario_nombre.setEditable(false);
        in_usuario_nombre.setBackground(new java.awt.Color(200, 200, 200));
        in_usuario_nombre.setText("USUARIO");
        in_usuario_nombre.setFocusable(false);
        in_usuario_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                in_usuario_nombreFocusGained(evt);
            }
        });
        in_usuario_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_usuario_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(in_usuario_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 30));

        in_libro_titulo.setEditable(false);
        in_libro_titulo.setBackground(new java.awt.Color(200, 200, 200));
        in_libro_titulo.setText("LIBRO");
        in_libro_titulo.setFocusable(false);
        in_libro_titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                in_libro_tituloFocusGained(evt);
            }
        });
        getContentPane().add(in_libro_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 30));

        in_libro_codigo.setEditable(false);
        in_libro_codigo.setBackground(new java.awt.Color(200, 200, 200));
        in_libro_codigo.setText("COD LIBRO");
        in_libro_codigo.setFocusable(false);
        in_libro_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                in_libro_codigoFocusGained(evt);
            }
        });
        in_libro_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_libro_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(in_libro_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 90, 30));

        BotonGuardado.setBackground(new java.awt.Color(100, 180, 100));
        BotonGuardado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonGuardado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonGuardado.setText("GUARDAR");
        BotonGuardado.setFocusable(false);
        BotonGuardado.setOpaque(true);
        BotonGuardado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonGuardadoMousePressed(evt);
            }
        });
        BotonGuardado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseMoved(evt);
            }
        });
        getContentPane().add(BotonGuardado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 80, 40));

        BotonSalida.setBackground(new java.awt.Color(100, 180, 100));
        BotonSalida.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalida.setText("VOLVER");
        BotonSalida.setFocusable(false);
        BotonSalida.setOpaque(true);
        BotonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalidaMousePressed(evt);
            }
        });
        BotonSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseMoved(evt);
            }
        });
        getContentPane().add(BotonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 40));

        lb_aviso.setBackground(new java.awt.Color(55, 55, 55));
        lb_aviso.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lb_aviso.setForeground(new java.awt.Color(255, 0, 0));
        lb_aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_aviso.setText("AVISO");
        lb_aviso.setOpaque(true);
        getContentPane().add(lb_aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 40));

        Lbfondo.setBackground(new java.awt.Color(55, 55, 55));
        Lbfondo.setOpaque(true);
        getContentPane().add(Lbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded

    }//GEN-LAST:event_jTable1ComponentAdded

    private void boton_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseClicked

        lb_aviso.setText("Ingreso Nuevo");

        in_fec_Prestamo.setFocusable(true);
        in_fec_Prestamo.setEditable(true);
        in_fec_Prestamo.setBackground(Color.white);
        in_fec_Prestamo.hasFocus();

        in_fec_Devolucion.setFocusable(true);
        in_fec_Devolucion.setEditable(true);
        in_fec_Devolucion.setBackground(Color.white);

        in_usuario_nombre.setFocusable(true);
        in_usuario_nombre.setEditable(true);
        in_usuario_nombre.setBackground(Color.white);

        in_libro_titulo.setFocusable(true);
        in_libro_titulo.setEditable(true);
        in_libro_titulo.setBackground(Color.white);

        in_usuario_codigo.setFocusable(true);
        in_usuario_codigo.setEditable(true);
        in_usuario_codigo.setBackground(Color.white);

        in_libro_codigo.setFocusable(true);
        in_libro_codigo.setEditable(true);
        in_libro_codigo.setBackground(Color.white);

        in_codigo.setText("AUTO");

    }//GEN-LAST:event_boton_nuevoMouseClicked

    private void boton_nuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseEntered

        Color bColor=new Color(100,100,100);
        boton_nuevo.setBackground(bColor);
    }//GEN-LAST:event_boton_nuevoMouseEntered

    private void boton_nuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseExited

        Color bColor=new Color(55,55,55);
        boton_nuevo.setBackground(bColor);
    }//GEN-LAST:event_boton_nuevoMouseExited

    private void boton_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_editarMouseClicked

        Color lbColor=new Color(200,200,200);

        lb_aviso.setText("Elija de la tabla");

         in_fec_Prestamo.setFocusable(true);
        in_fec_Prestamo.setEditable(true);
        in_fec_Prestamo.setBackground(Color.white);
        in_fec_Prestamo.hasFocus();

        in_fec_Devolucion.setFocusable(true);
        in_fec_Devolucion.setEditable(true);
        in_fec_Devolucion.setBackground(Color.white);

        in_usuario_nombre.setFocusable(true);
        in_usuario_nombre.setEditable(true);
        in_usuario_nombre.setBackground(Color.white);

        in_libro_titulo.setFocusable(true);
        in_libro_titulo.setEditable(true);
        in_libro_titulo.setBackground(Color.white);

        in_usuario_codigo.setFocusable(true);
        in_usuario_codigo.setEditable(true);
        in_usuario_codigo.setBackground(Color.white);

        in_libro_codigo.setFocusable(true);
        in_libro_codigo.setEditable(true);
        in_libro_codigo.setBackground(Color.white);

        //in_codigo.setText("Codigo");
    }//GEN-LAST:event_boton_editarMouseClicked

    private void boton_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_editarMouseEntered

        Color bColor=new Color(100,100,100);
        boton_editar.setBackground(bColor);
    }//GEN-LAST:event_boton_editarMouseEntered

    private void boton_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_editarMouseExited

        Color bColor=new Color(55,55,55);
        boton_editar.setBackground(bColor);
    }//GEN-LAST:event_boton_editarMouseExited

    private void boton_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_borrarMouseClicked

        Color lbColor=new Color(200,200,200);

        lb_aviso.setText("NO DISPONIBLE");

        in_fec_Prestamo.setEditable(false);
        in_fec_Prestamo.setBackground(lbColor);
        in_fec_Prestamo.setFocusable(false);

        in_fec_Devolucion.setEditable(false);
        in_fec_Devolucion.setBackground(lbColor);
        in_fec_Devolucion.setFocusable(false);

        in_usuario_nombre.setEditable(false);
        in_usuario_nombre.setBackground(lbColor);
        in_usuario_nombre.setFocusable(false);

        in_libro_titulo.setEditable(false);
        in_libro_titulo.setBackground(lbColor);
        in_libro_titulo.setFocusable(false);

        in_usuario_codigo.setEditable(false);
        in_usuario_codigo.setBackground(lbColor);
        in_usuario_codigo.setFocusable(false);

        in_libro_codigo.setEditable(false);
        in_libro_codigo.setBackground(lbColor);
        in_libro_codigo.setFocusable(false);

        in_codigo.setText("Codigo");
    }//GEN-LAST:event_boton_borrarMouseClicked

    private void boton_borrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_borrarMouseEntered

        Color bColor=new Color(100,100,100);
        boton_borrar.setBackground(bColor);
    }//GEN-LAST:event_boton_borrarMouseEntered

    private void boton_borrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_borrarMouseExited

        Color bColor=new Color(55,55,55);
        boton_borrar.setBackground(bColor);
    }//GEN-LAST:event_boton_borrarMouseExited

    private void in_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_codigoKeyTyped

        char c = evt.getKeyChar();
        if((c<'0' || c>'9'))evt.consume();
    }//GEN-LAST:event_in_codigoKeyTyped

    private void in_fec_PrestamoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_fec_PrestamoFocusGained

        in_fec_Prestamo.selectAll();
    }//GEN-LAST:event_in_fec_PrestamoFocusGained

    private void in_fec_DevolucionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_fec_DevolucionFocusGained
        in_fec_Devolucion.selectAll();
    }//GEN-LAST:event_in_fec_DevolucionFocusGained

    private void in_fec_DevolucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_fec_DevolucionKeyTyped

        char c = evt.getKeyChar();
        if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' '))evt.consume();
    }//GEN-LAST:event_in_fec_DevolucionKeyTyped

    private void in_usuario_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_usuario_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_usuario_codigoActionPerformed

    private void in_usuario_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_usuario_codigoFocusGained
        in_usuario_codigo.selectAll();
    }//GEN-LAST:event_in_usuario_codigoFocusGained

    private void in_usuario_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_usuario_codigoKeyTyped

        char c = evt.getKeyChar();
        if((c<'0' || c>'9'))evt.consume();
    }//GEN-LAST:event_in_usuario_codigoKeyTyped

    private void in_usuario_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_usuario_nombreFocusGained
        in_usuario_nombre.selectAll();
    }//GEN-LAST:event_in_usuario_nombreFocusGained

    private void in_usuario_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_usuario_nombreKeyTyped

        char c = evt.getKeyChar();
        if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' '))evt.consume();
    }//GEN-LAST:event_in_usuario_nombreKeyTyped

    private void in_libro_tituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_libro_tituloFocusGained
        in_libro_titulo.selectAll();
    }//GEN-LAST:event_in_libro_tituloFocusGained

    private void in_libro_codigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_libro_codigoFocusGained
        in_libro_codigo.selectAll();
    }//GEN-LAST:event_in_libro_codigoFocusGained

    private void in_libro_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_libro_codigoKeyTyped

        char c = evt.getKeyChar();
        if((c<'0' || c>'9'))evt.consume();
    }//GEN-LAST:event_in_libro_codigoKeyTyped

    private void BotonGuardadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseClicked

        Conexion con = new Conexion();
        Connection conn = con.Conectar();
        Statement stm=null;

        String cad1,cad2,cad3,cad4,cad5,cad6;
        cad1=in_fec_Prestamo.getText();
        cad2=in_fec_Devolucion.getText();
        cad3=in_usuario_nombre.getText();
        cad4=in_libro_titulo.getText();
        cad5=in_usuario_codigo.getText();
        cad6=in_libro_codigo.getText();
        String ins=null;

        if ((in_fec_Prestamo.getText().equals("")) || (in_fec_Devolucion.getText().equals("")) || (in_usuario_nombre.getText().equals("")) || in_libro_titulo.getText().equals("") || (in_usuario_codigo.getText().equals("")) || (in_libro_codigo.getText().equals(""))) {

            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            in_fec_Prestamo.requestFocus();
        }
        else {

            ins = "INSERT INTO `biblioteca`.`libro` (`Titulo`, `Autor`, `Anio_Publi`,`Genero`,`Editorial`) VALUES ('"+cad1+"', '"+cad2+"', '"+cad5+"', '"+cad3+"', '"+cad4+"')";
        }
        try{
            stm=conn.createStatement();
            stm.executeUpdate(ins);
        } catch (SQLException ex) {
            Logger.getLogger(Libros.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.boton_nuevoMouseClicked(evt);

    }//GEN-LAST:event_BotonGuardadoMouseClicked

    private void BotonGuardadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseEntered

        Color bColor1=new Color(151,195,151);
        BotonGuardado.setBackground(bColor1);
    }//GEN-LAST:event_BotonGuardadoMouseEntered

    private void BotonGuardadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseExited

        Color bColor2=new Color(100,180,100);
        BotonGuardado.setBackground(bColor2);
    }//GEN-LAST:event_BotonGuardadoMouseExited

    private void BotonGuardadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMousePressed

        Color bColor3=new Color(171,225,171);
        BotonGuardado.setBackground(bColor3);
    }//GEN-LAST:event_BotonGuardadoMousePressed

    private void BotonGuardadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseMoved

        Color bColor3=new Color(151,195,151);
        BotonGuardado.setBackground(bColor3);
    }//GEN-LAST:event_BotonGuardadoMouseMoved

    private void BotonSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseClicked

        rootPane.setVisible(false);
        dispose();
        MenuP m = new MenuP();
        m.setVisible(true);

    }//GEN-LAST:event_BotonSalidaMouseClicked

    private void BotonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseEntered
        Color bColor1=new Color(151,195,151);
        BotonSalida.setBackground(bColor1);
    }//GEN-LAST:event_BotonSalidaMouseEntered

    private void BotonSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseExited
        Color bColor2=new Color(100,180,100);
        BotonSalida.setBackground(bColor2);
    }//GEN-LAST:event_BotonSalidaMouseExited

    private void BotonSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMousePressed
        Color bColor3=new Color(171,225,171);
        BotonSalida.setBackground(bColor3);
    }//GEN-LAST:event_BotonSalidaMousePressed

    private void BotonSalidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseMoved
        Color bColor3=new Color(151,195,151);
        BotonSalida.setBackground(bColor3);
    }//GEN-LAST:event_BotonSalidaMouseMoved

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonGuardado;
    private javax.swing.JLabel BotonSalida;
    private javax.swing.JLabel Lbfondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel boton_borrar;
    private javax.swing.JLabel boton_editar;
    private javax.swing.JLabel boton_nuevo;
    private javax.swing.JTextField in_codigo;
    private javax.swing.JTextField in_fec_Devolucion;
    private javax.swing.JTextField in_fec_Prestamo;
    private javax.swing.JTextField in_libro_codigo;
    private javax.swing.JTextField in_libro_titulo;
    private javax.swing.JTextField in_usuario_codigo;
    private javax.swing.JTextField in_usuario_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_aviso;
    // End of variables declaration//GEN-END:variables
}
