/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaE;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Usuarios extends javax.swing.JFrame {

    public Usuarios() {
        initComponents();
        lb_aviso.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblibros = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        BotonActualizar = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        boton_nuevo = new javax.swing.JLabel();
        boton_editar = new javax.swing.JLabel();
        boton_borrar = new javax.swing.JLabel();
        in_nombre = new javax.swing.JTextField();
        in_apellido = new javax.swing.JTextField();
        in_cedula = new javax.swing.JTextField();
        in_codigo = new javax.swing.JTextField();
        BotonGuardado = new javax.swing.JLabel();
        BotonSalida = new javax.swing.JLabel();
        lb_aviso = new javax.swing.JLabel();
        Lbfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Usuarios"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idusuarios", "Nombre", "Apellido", "Cedula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblibros.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tblibrosComponentAdded(evt);
            }
        });
        tblibros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblibrosFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblibros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 560, 300));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 10, 370));

        BotonActualizar.setBackground(new java.awt.Color(100, 180, 100));
        BotonActualizar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonActualizar.setText("ATUALIZAR");
        BotonActualizar.setFocusable(false);
        BotonActualizar.setOpaque(true);
        BotonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonActualizarMousePressed(evt);
            }
        });
        BotonActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonActualizarMouseMoved(evt);
            }
        });
        getContentPane().add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, 30));

        Titulo.setBackground(new java.awt.Color(100, 180, 100));
        Titulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("USUARIOS");
        Titulo.setToolTipText("");
        Titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Titulo.setOpaque(true);
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        boton_nuevo.setBackground(new java.awt.Color(55, 55, 55));
        boton_nuevo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        boton_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_nuevo.setText("NUEVO");
        boton_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_nuevo.setOpaque(true);
        boton_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_nuevoMouseExited(evt);
            }
        });
        getContentPane().add(boton_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        boton_editar.setBackground(new java.awt.Color(55, 55, 55));
        boton_editar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_editar.setForeground(new java.awt.Color(255, 255, 255));
        boton_editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_editar.setText("EDITAR");
        boton_editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_editar.setOpaque(true);
        boton_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_editarMouseExited(evt);
            }
        });
        getContentPane().add(boton_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, 30));

        boton_borrar.setBackground(new java.awt.Color(55, 55, 55));
        boton_borrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_borrar.setForeground(new java.awt.Color(255, 255, 255));
        boton_borrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_borrar.setText("BORRAR");
        boton_borrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        boton_borrar.setOpaque(true);
        boton_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_borrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_borrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_borrarMouseExited(evt);
            }
        });
        getContentPane().add(boton_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 80, 30));

        in_nombre.setEditable(false);
        in_nombre.setBackground(new java.awt.Color(200, 200, 200));
        in_nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        in_nombre.setText("NOMBRE");
        in_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        in_nombre.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        in_nombre.setFocusable(false);
        in_nombre.setSelectionColor(new java.awt.Color(100, 100, 100));
        in_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_nombreActionPerformed(evt);
            }
        });
        in_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(in_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 30));

        in_apellido.setEditable(false);
        in_apellido.setBackground(new java.awt.Color(200, 200, 200));
        in_apellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        in_apellido.setText("APELLIDO");
        in_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        in_apellido.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        in_apellido.setFocusable(false);
        in_apellido.setSelectionColor(new java.awt.Color(100, 100, 100));
        in_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_apellidoKeyTyped(evt);
            }
        });
        getContentPane().add(in_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 30));

        in_cedula.setEditable(false);
        in_cedula.setBackground(new java.awt.Color(200, 200, 200));
        in_cedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        in_cedula.setText("CEDULA");
        in_cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        in_cedula.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        in_cedula.setFocusable(false);
        in_cedula.setSelectionColor(new java.awt.Color(100, 100, 100));
        in_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_cedulaKeyTyped(evt);
            }
        });
        getContentPane().add(in_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 30));

        in_codigo.setEditable(false);
        in_codigo.setBackground(new java.awt.Color(200, 200, 200));
        in_codigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        in_codigo.setText("CODIGO");
        in_codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        in_codigo.setDisabledTextColor(new java.awt.Color(50, 50, 50));
        in_codigo.setFocusable(false);
        in_codigo.setSelectionColor(new java.awt.Color(100, 100, 100));
        in_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                in_codigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                in_codigoKeyTyped(evt);
            }
        });
        getContentPane().add(in_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 80, 30));

        BotonGuardado.setBackground(new java.awt.Color(100, 180, 100));
        BotonGuardado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonGuardado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonGuardado.setText("GUARDAR");
        BotonGuardado.setFocusable(false);
        BotonGuardado.setOpaque(true);
        BotonGuardado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseMoved(evt);
            }
        });
        BotonGuardado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonGuardadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonGuardadoMousePressed(evt);
            }
        });
        getContentPane().add(BotonGuardado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 80, 40));

        BotonSalida.setBackground(new java.awt.Color(100, 180, 100));
        BotonSalida.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BotonSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalida.setText("VOLVER");
        BotonSalida.setFocusable(false);
        BotonSalida.setOpaque(true);
        BotonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalidaMousePressed(evt);
            }
        });
        BotonSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BotonSalidaMouseMoved(evt);
            }
        });
        getContentPane().add(BotonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 40));

        lb_aviso.setBackground(new java.awt.Color(55, 55, 55));
        lb_aviso.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        lb_aviso.setForeground(new java.awt.Color(255, 0, 0));
        lb_aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_aviso.setText("AVISO");
        lb_aviso.setOpaque(true);
        getContentPane().add(lb_aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 40));

        Lbfondo.setBackground(new java.awt.Color(55, 55, 55));
        Lbfondo.setOpaque(true);
        getContentPane().add(Lbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_nuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseEntered
        
        Color bColor=new Color(100,100,100);
           boton_nuevo.setBackground(bColor);
    }//GEN-LAST:event_boton_nuevoMouseEntered

    private void boton_nuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseExited

        Color bColor=new Color(55,55,55);
        boton_nuevo.setBackground(bColor);
    }//GEN-LAST:event_boton_nuevoMouseExited

    private void boton_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_editarMouseEntered
      
        Color bColor=new Color(100,100,100);
        boton_editar.setBackground(bColor);
    }//GEN-LAST:event_boton_editarMouseEntered

    private void boton_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_editarMouseExited
  
        Color bColor=new Color(55,55,55);
        boton_editar.setBackground(bColor);
    }//GEN-LAST:event_boton_editarMouseExited

    private void boton_borrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_borrarMouseEntered

        Color bColor=new Color(100,100,100);
        boton_borrar.setBackground(bColor);
    }//GEN-LAST:event_boton_borrarMouseEntered

    private void boton_borrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_borrarMouseExited

        Color bColor=new Color(55,55,55);
        boton_borrar.setBackground(bColor);
    }//GEN-LAST:event_boton_borrarMouseExited

    private void BotonSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseClicked

        rootPane.setVisible(false);
       dispose();
        MenuP m = new MenuP();
        m.setVisible(true);    
    }//GEN-LAST:event_BotonSalidaMouseClicked

    private void BotonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseEntered
    
        Color bColor1=new Color(151,195,151);
        BotonSalida.setBackground(bColor1);
    }//GEN-LAST:event_BotonSalidaMouseEntered

    private void BotonSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseExited

          Color bColor2=new Color(100,180,100);
        BotonSalida.setBackground(bColor2);
    }//GEN-LAST:event_BotonSalidaMouseExited

    private void BotonSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMousePressed

         Color bColor3=new Color(171,225,171);
        BotonSalida.setBackground(bColor3);
    }//GEN-LAST:event_BotonSalidaMousePressed

    private void BotonSalidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalidaMouseMoved

              Color bColor3=new Color(151,195,151);
        BotonSalida.setBackground(bColor3);
    }//GEN-LAST:event_BotonSalidaMouseMoved

    private void in_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_nombreKeyTyped

        char c = evt.getKeyChar();
        if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' '))evt.consume();
    }//GEN-LAST:event_in_nombreKeyTyped

    private void in_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_cedulaKeyTyped

         char c = evt.getKeyChar();
        if((c<'0' || c>'9'))evt.consume();
    }//GEN-LAST:event_in_cedulaKeyTyped

    private void in_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_codigoKeyTyped

         char c = evt.getKeyChar();
        if((c<'0' || c>'9'))evt.consume();
    }//GEN-LAST:event_in_codigoKeyTyped

    private void in_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_apellidoKeyTyped

        char c = evt.getKeyChar();
        if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' '))evt.consume();
    }//GEN-LAST:event_in_apellidoKeyTyped

    private void BotonGuardadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseClicked
        
           Conexion con = new Conexion();
           Connection conn = con.Conectar();
           Statement stm=null;
        
        
        String cad1,cad2,cad3,cad4,cad5;
       cad1=in_nombre.getText();
       cad2=in_apellido.getText();
       cad3=in_cedula.getText();
       cad4=in_codigo.getText();
       cad4="1";
       String ins=null;
       
      if ((in_cedula.getText().equals("")) || (in_codigo.getText().equals("")) || in_nombre.getText().equals("") || (in_apellido.getText().equals(""))) {
            
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            in_nombre.requestFocus();
        }
      else {
      
        ins = "INSERT INTO `biblioteca`.`usuarios` (`Nombre`, `Apellido`, `Cedula`) VALUES ('"+cad1+"', '"+cad2+"', '"+cad3+"')";
      }
      try{
          stm=conn.createStatement();
          stm.executeUpdate(ins);
      } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
   this.boton_nuevoMouseClicked(evt);

    }//GEN-LAST:event_BotonGuardadoMouseClicked

    private void BotonGuardadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseEntered
       
        Color bColor1=new Color(151,195,151);
        BotonGuardado.setBackground(bColor1);  
    }//GEN-LAST:event_BotonGuardadoMouseEntered

    private void BotonGuardadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseExited
   
        Color bColor1=new Color(100,180,100);
        BotonGuardado.setBackground(bColor1);  
    }//GEN-LAST:event_BotonGuardadoMouseExited

    private void BotonGuardadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMousePressed
        
        Color bColor3=new Color(171,225,171);
        BotonGuardado.setBackground(bColor3);
    }//GEN-LAST:event_BotonGuardadoMousePressed

    private void BotonGuardadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardadoMouseMoved
        
            Color bColor3=new Color(151,195,151);
        BotonGuardado.setBackground(bColor3);
    }//GEN-LAST:event_BotonGuardadoMouseMoved

    private void boton_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nuevoMouseClicked

        lb_aviso.setText("Ingreso Nuevo");
        
        in_nombre.setFocusable(true);
        in_nombre.setEditable(true);
        in_nombre.setBackground(Color.white);
        in_nombre.hasFocus();
       
        
        in_apellido.setFocusable(true);
        in_apellido.setEditable(true);
        in_apellido.setBackground(Color.white);
        
 
        in_cedula.setFocusable(true);
        in_cedula.setEditable(true);
        in_cedula.setBackground(Color.white);
                
        in_codigo.setText("AUTO");
    }//GEN-LAST:event_boton_nuevoMouseClicked

    private void boton_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_editarMouseClicked

        Color lbColor=new Color(200,200,200);
        
        lb_aviso.setText("NO DISPONIBLE");
        
        in_nombre.setEditable(false);
        in_nombre.setBackground(lbColor);
        in_nombre.setFocusable(false);
                
        in_apellido.setEditable(false);
        in_apellido.setBackground(lbColor);
        in_apellido.setFocusable(false);
 
        in_cedula.setEditable(false);
        in_cedula.setBackground(lbColor);
        in_cedula.setFocusable(false);
                
        in_codigo.setText("Codigo");
    }//GEN-LAST:event_boton_editarMouseClicked

    private void boton_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_borrarMouseClicked

        Color lbColor=new Color(200,200,200);
        
        lb_aviso.setText("NO DISPONIBLE");
        
        in_nombre.setEditable(false);
        in_nombre.setBackground(lbColor);
        in_nombre.setFocusable(false);
                
        in_apellido.setEditable(false);
        in_apellido.setBackground(lbColor);
        in_apellido.setFocusable(false);
 
        in_cedula.setEditable(false);
        in_cedula.setBackground(lbColor);
        in_cedula.setFocusable(false);
                
        in_codigo.setText("Codigo");
    }//GEN-LAST:event_boton_borrarMouseClicked

    private void in_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_nombreActionPerformed

    private void in_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_codigoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_codigoKeyPressed

    private void tblibrosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblibrosComponentAdded

    }//GEN-LAST:event_tblibrosComponentAdded

    private void tblibrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblibrosFocusGained

    }//GEN-LAST:event_tblibrosFocusGained

    private void BotonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarMouseClicked
        // TODO add your handling code here:
       /* Libros_P = db.listarLibros();
        DefaultTableModel tb=(DefaultTableModel)tblibros.getModel();
        for(Libros_Principal libros: Libros_P){
            limpiarformulario();
            tb.addRow(new Object[]{libros.getIdlibro(),libros.getTitulo(),libros.getAutor(),libros.getAnio_Publi(),libros.getGenero(),libros.getEditorial()});
        }
*/
    }//GEN-LAST:event_BotonActualizarMouseClicked

    private void BotonActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarMouseEntered

    private void BotonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarMouseExited

    private void BotonActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarMousePressed

    private void BotonActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonActualizar;
    private javax.swing.JLabel BotonGuardado;
    private javax.swing.JLabel BotonSalida;
    private javax.swing.JLabel Lbfondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel boton_borrar;
    private javax.swing.JLabel boton_editar;
    private javax.swing.JLabel boton_nuevo;
    private javax.swing.JTextField in_apellido;
    private javax.swing.JTextField in_cedula;
    private javax.swing.JTextField in_codigo;
    private javax.swing.JTextField in_nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_aviso;
    private javax.swing.JTable tblibros;
    // End of variables declaration//GEN-END:variables
}
